### ISSUE TITLE
Misc - If no match is found for a file extension

### ISSUE THREAD

**Issue by fenilgmehta** [jgyasu/fileaway#2]
How about adding an `else` block to [move_files.py#L79](https://github.com/cheesemaafia/forganiser/blob/4458e02cb8c84bfac6727e984deb037e2ddb9b26/src/move_files.py#L79) and moving all unmatched file extensions to a folder called `Misc` ?

**Comment by jgyasu** [comment]
Thanks for the suggestion, implemented it :)
